### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by jwerardi** [tylerjbainbridge/MessagingApp#6]
https://docs.docker.com/engine/installation/linux/ubuntu/

http://laradock.io/

**Comment by jwerardi** [comment]
```
version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: web.docker
        volumes:
            - ./:/var/www
        ports:
            - "8080:80"
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: app.docker
        volumes:
            - ./:/var/www
```
